# Generated by Django 2.2 on 2021-11-13 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHotelSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=10)),
                ('checkInDate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Length has to be 10', regex='^.{10}$')])),
                ('checkOutDate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Length has to be 10', regex='^.{10}$')])),
                ('adults', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlightsSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originplace', models.CharField(max_length=10)),
                ('destinationplace', models.CharField(max_length=10)),
                ('outbounddate', models.CharField(max_length=100)),
                ('inbounddate', models.CharField(blank=True, max_length=100)),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(blank=True, default=0)),
                ('infants', models.IntegerField(blank=True, default=0)),
                ('country', models.CharField(default='IN', max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightsHotelPackageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originplace', models.CharField(max_length=10)),
                ('destinationplace', models.CharField(max_length=10)),
                ('outbounddate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Length has to be 10', regex='^.{10}$')])),
                ('inbounddate', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Length has to be 10', regex='^.{10}$')])),
                ('adults', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.IntegerField(blank=True, default=0)),
                ('infants', models.IntegerField(blank=True, default=0)),
                ('country', models.CharField(default='IN', max_length=10)),
                ('currency_format', models.CharField(max_length=10)),
                ('destination_code', models.CharField(max_length=10)),
                ('locale', models.CharField(max_length=10)),
                ('trip_days', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('number_of_extended_months', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
