# Generated by Django 4.2.3 on 2023-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
